# Generated by Django 4.1.4 on 2023-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1983-08-20'),
            preserve_default=False,
        ),
    ]
